language: scala

scala:
  - 2.11.12
  - 2.12.10
  - 2.13.1
jdk:
  - openjdk8
env:
  matrix:
    - SCALAJS_VERSION=
    - SCALAJS_VERSION=0.6.28
    - SCALAJS_VERSION=1.0.0

script:
  - |
    if [ "$SCALAJS_VERSION" = "" ]; then
      PROJECT_NAME="portable-scala-reflectJVM"
    else
      PROJECT_NAME="portable-scala-reflectJS"
    fi
  - sbt ++$TRAVIS_SCALA_VERSION! $PROJECT_NAME/test
  - sbt ++$TRAVIS_SCALA_VERSION! $PROJECT_NAME/doc
  - sbt ++$TRAVIS_SCALA_VERSION! $PROJECT_NAME/mimaReportBinaryIssues

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
