language: scala

scala:
  - 2.11.12
  - 2.12.13
  - 2.13.4
jdk:
  - openjdk8
env:
  matrix:
    - SCALAJVM_VERSION=
    - SCALAJS_VERSION=0.6.33
    - SCALAJS_VERSION=1.0.1
    - SCALANATIVE_VERSION=

script:
  - |
    [ -v SCALAJVM_VERSION ]    && PROJECT_PLATFORM="JVM"
    [ -v SCALAJS_VERSION ]     && PROJECT_PLATFORM="JS"
    [ -v SCALANATIVE_VERSION ] && PROJECT_PLATFORM="Native"
    PROJECT_NAME="portable-scala${PROJECT_PLATFORM}"

  - sbt ++$TRAVIS_SCALA_VERSION! $PROJECT_NAME/test
  - sbt ++$TRAVIS_SCALA_VERSION! $PROJECT_NAME/doc
  - sbt ++$TRAVIS_SCALA_VERSION! $PROJECT_NAME/mimaReportBinaryIssues

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
